# Generated by Django 5.2.15 on 2026-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_boardinghouse_inquiry_reservation_review_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, default='boarding_houses/img1.jpg', upload_to='boarding_houses/'),
        ),
    ]
