# Generated by Django 6.0.4 on 2026-07-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_boardinghouse_image_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_houses/'),
        ),
    ]
