# Generated by Django 6.0.4 on 2026-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_boardinghouse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Special requests or notes from the tenant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Pre-computed total in PHP', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
