# Generated by Django 6.0.4 on 2026-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_reservation_check_out_date_reservation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_type',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('booking', 'Booking')], default='reservation', max_length=20),
        ),
    ]
