# Generated by Django 6.0.4 on 2026-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_reservation_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date the room becomes available (optional)', null=True),
        ),
    ]
